//Autogenerated verilog on 2015-05-05 15:25:22.648715

`timescale 1 ns / 1 ps

module channel_id
(
  input clk,
  output reg CAL,
  output CS,
  output reg IS1,
  output reg IS2,
  output reg LE,
  output reg R12,
  output reg RBI,
  output reg RESET,
  output reg RPHI1,
  output reg RPHI2,
  output reg SBI,
  output reg SEB,
  output reg SPHI1,
  output reg SPHI2,
  output reg SR,
  input reset_gen
);

reg [31:0]counter;
reg [7:0]stage;
reg [15:0]stage_iter;
assign CS=0;
always @(posedge clk ) begin
  if(reset_gen == 1) begin
    counter <= 0;
    stage <= 0;
    stage_iter <= 0;
  end
  else begin
    if(stage == 0) begin
      if(counter == 0) begin
        CAL <= 1;
        SBI <= 1;
        SPHI1 <= 1;
        SPHI2 <= 1;
        SEB <= 1;
        IS1 <= 1;
        IS2 <= 1;
        SR <= 1;
        RESET <= 1;
        R12 <= 1;
        RBI <= 1;
        RPHI1 <= 1;
        RPHI2 <= 1;
        LE <= 1;
      end
      if(counter == 1) begin
        CAL <= 0;
        SBI <= 0;
        SPHI1 <= 0;
        SPHI2 <= 0;
        SEB <= 0;
        IS1 <= 0;
        IS2 <= 0;
        SR <= 0;
        RESET <= 0;
        R12 <= 0;
        RBI <= 0;
        RPHI1 <= 0;
        RPHI2 <= 0;
        LE <= 0;
      end
      if(counter == 4) begin
        CAL <= 1;
        SBI <= 1;
        SPHI1 <= 1;
        SPHI2 <= 1;
        SEB <= 1;
        IS1 <= 1;
        IS2 <= 1;
        SR <= 1;
        RESET <= 1;
        R12 <= 1;
        RBI <= 1;
        RPHI1 <= 1;
        RPHI2 <= 1;
        LE <= 1;
      end
      if(counter == 5) begin
        CAL <= 0;
        SBI <= 0;
        SPHI1 <= 0;
        SPHI2 <= 0;
        SEB <= 0;
        IS1 <= 0;
        IS2 <= 0;
      end
      if(counter == 6) begin
        SPHI2 <= 1;
        SEB <= 1;
        IS1 <= 1;
        IS2 <= 1;
        SR <= 0;
        RESET <= 0;
        R12 <= 0;
        RBI <= 0;
      end
      if(counter == 7) begin
        SBI <= 1;
        SPHI1 <= 1;
        SPHI2 <= 0;
        SEB <= 0;
        R12 <= 1;
        RBI <= 1;
        RPHI1 <= 0;
        RPHI2 <= 0;
      end
      if(counter == 8) begin
        CAL <= 1;
        SBI <= 0;
        SEB <= 1;
        IS1 <= 0;
        RESET <= 1;
        R12 <= 0;
        RPHI2 <= 1;
      end
      if(counter == 8) begin
        if(stage_iter == 0) begin
          stage <= (stage + 1) % 2;
          stage_iter <= 0;
        end
        else begin
          stage_iter <= stage_iter + 1;
        end
        counter <= 0;
      end
      else begin
        counter <= counter + 1;
      end
    end
    if(stage == 1) begin
      if(counter == 0) begin
        CAL <= 0;
        SBI <= 0;
        SPHI1 <= 0;
        SPHI2 <= 0;
        SEB <= 0;
        IS1 <= 0;
        IS2 <= 0;
        SR <= 0;
        RESET <= 0;
        R12 <= 0;
        RBI <= 0;
        RPHI1 <= 0;
        RPHI2 <= 0;
        LE <= 0;
      end
      if(counter == 3) begin
        if(stage_iter == 49) begin
          stage <= (stage + 1) % 2;
          stage_iter <= 0;
        end
        else begin
          stage_iter <= stage_iter + 1;
        end
        counter <= 0;
      end
      else begin
        counter <= counter + 1;
      end
    end
  end
end
endmodule